apiVersion: v1
kind: Service
metadata:
  name: service-symfony-shopapp-new3
  labels:
    app: symfony-shopapp-new3
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  selector:
    app: symfony-shopapp-new3
    type: fe-end
