
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv31
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc32
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi