<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => '%%APPSECRET%%',
  'DATABASE_URL' => 'mysql://%%DBUS%%:%%DBPASS%%@%%DBHOST%%:%%DBPORT%%/%%DBNAME%%',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '%%JWTPASSPHRASE%%',
  'MERCURE_URL' => 'https://example.com/.well-known/mercure',
  'MERCURE_PUBLIC_URL' => 'https://example.com/.well-known/mercure',
  'MERCURE_JWT_SECRET' => '%%MERCUREJWTSECRET%%',
);
