# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: _test

on:
  workflow_call:
permissions:
  contents: read
defaults:
 run:
  working-directory: ./app
env:
  REGISTRY: faezsal
  IMAGE_NAME: symfony-shop-app
jobs:
  InitTest:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
