# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: _docker

on:
  workflow_call:
permissions:
  contents: read
defaults:
 run:
  working-directory: ./app
env:
  REGISTRY: faezsal
  IMAGE_NAME: symfony-shop-app
jobs:
  InitTest:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

  push-docker-image:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: display the fodler
        run: |
          pwd
          ls
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build env file 
        run: sed  -i  's/%%APPSECRET%%/${{ secrets.APPSECRET }}/g' .env.dist
      - name: Build env file 
        run: sed  -i  's/%%DBUS%%/${{ secrets.DBUS }}/g' .env.dist
      - name: Build env file 
        run: sed  -i  's/%%DBPASS%%/${{ secrets.DBPASS }}/g' .env.dist
      - name: Build env file 
        run: sed  -i  's/%%DBHOST%%/${{ secrets.DBHOST }}/g' .env.dist
      - name: Build env file 
        run: sed  -i  's/%%DBNAME%%/${{ secrets.DBNAME }}/g' .env.dist
      - name: Build env file 
        run: sed  -i  's/%%DBPORT%%/${{ secrets.DBPORT }}/g' .env.dist

      - name: Build env file 
        run: sed  -i  's/%%JWTPASSPHRASE%%/${{ secrets.JWTPASSPHRASE }}/g' .env.dist
      - name: Build env file 
        run: sed  -i  's/%%MERCUREJWTSECRET%%/${{ secrets.MERCUREJWTSECRET }}/g' .env.dist
      - name: Replace env file
        run: |
          rm .env
          mv .env.dist .env
      - name: Cat .env
        run: cat .env
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: ls 
        run: composer dump-env prod
      - name: remove cache
        run: rm -rf var/cache/dev 
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ../container/symfony/
          dockerfile: ../container/symfony/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}