# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: _docker

on:
  workflow_call:
permissions:
  contents: read
defaults:
 run:
  working-directory: ./app
env:
  REGISTRY: faezsal
  IMAGE_NAME: symfony-shop-app
jobs:
  InitTest:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  docker-push:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: shopnewnew
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Check file existence
      env:
        FILE: .env.dist
      shell: bash
      run: |
        if [[ -f $FILE ]]; then
          echo "$FILE exists!"
        else
          echo "$FILE does not exist!"
        fi
    - name: display the fodler
      run: |
        pwd
        ls
    - name: Build env file
      run: |
        sed  -i  's/%%APPSECRET%%/${{ secrets.APPSECRET }}/g' .env.dist
        sed  -i  's/%%DBUS%%/${{ secrets.DBUS }}/g' .env.dist
        sed  -i  's/%%DBPASS%%/${{ secrets.DBPASS }}/g' .env.dist
        sed  -i  's/%%DBHOST%%/${{ secrets.DBHOST }}/g' .env.dist
        sed  -i  's/%%DBNAME%%/${{ secrets.DBNAME }}/g' .env.dist
        sed  -i  's/%%DBPORT%%/${{ secrets.DBPORT }}/g' .env.dist
        sed  -i  's/%%JWTPASSPHRASE%%/${{ secrets.JWTPASSPHRASE }}/g' .env.dist
        sed  -i  's/%%MERCUREJWTSECRET%%/${{ secrets.MERCUREJWTSECRET }}/g' .env.dist
    - name: Replace env file
      run: |
        rm .env
        mv .env.dist .env
    - name: Cat .env
      run: cat .env
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: remove vendor
      run: rm -rf var/cache/dev
    - name: Set App Environemnt
      run: export APP_ENV=prod
    - name: Configure Environment Variables
      run: composer dump-env prod
    - name: Install Dependencies
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_DATABASE: shopnewnew
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: root
        DATABASE_URL: mysql://root:root@127.0.0.1:3306/shopnewnew
      run: composer install --no-dev --optimize-autoloader
    - name: generate jwt pair keys
      run: php bin/console lexik:jwt:generate-keypair

    - name: remove cache
      run: APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
    - name: login to docker registry
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: build and push docker image to registry
      uses: docker/build-push-action@v5
      with:
        context: ./container/symfony/
        dockerfile: ./container/symfony/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}