# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CL

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-phpqa:
    name: phpqa
    uses: ./.github/workflows/_phpqa.yml
    secrets: inherit


