# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CL

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  run-phpqa:
    name: phpqa
    uses: ./.github/workflows/_phpqa.yml
    secrets: inherit
  run-tests:
    needs: [ run-phpqa]
    name: Test
    uses: ./.github/workflows/_test.yml
    secrets: inherit
  run-docker:
    needs: [ run-tests]
    name: Docker
    uses: ./.github/workflows/_docker.yml
    secrets: inherit
